openapi: 3.1.0

info:
  title: Attachment
  version: 2.0.0
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
    identifier: Apache-2.0

components:
  schemas:
    Attachment:
      description: An attachment is a file that is attached to an entity.
      externalDocs:
        url: https://datamodel.tmforum.org/en/latest/Common/EntityAttachment
      allOf:
        - $ref: "./StatusEntity.openapi.yaml#/components/schemas/StatusEntity"
      required:
        - name
      properties:
        "@type":
          default: Attachment
          example: Attachment
        "@baseType":
          default: Attachment
          example: Attachment
        name:
          description: Name of the attachment.
          type: string
          example: image.jpg
        description:
          description: Description of the attachment.
          type: string
          example: Image of the product
        mimeType:
          description: The mime type of the attachment.
          type: string
          readOnly: true
          example: image/jpeg
        size:
          description: The size of the attachment in bytes.
          type: integer
          format: int64
          readOnly: true
        uri:
          description: Uniform Resource Identifier (URI) of the attachment.
          type: string
          readOnly: true
        relatedEntity:
          description: The entities related to the attachment.
          type: array
          items:
            $ref: "./RelatedEntity.openapi.yaml#/components/schemas/RelatedEntity"
          readOnly: true
        relatedParty:
          description: The parties related to the attachment.
          type: array
          items:
            $ref: "./RelatedEntity.openapi.yaml#/components/schemas/RelatedEntity"
          readOnly: true
        md5:
          description: The MD5 hash of the attachment.
          type: string
          readOnly: true
          example: 24ac5310315b1687111551f6646456d1
        sha1:
          description: The SHA1 hash of the attachment.
          type: string
          readOnly: true
          example: 92175a2c231f31ba757bc8e7620b7168707277ba
        sha256:
          description: The SHA256 hash of the attachment.
          type: string
          readOnly: true
          example: 8cf1bc0fca7f4158b8eb807be15fd7fd21bfe52d956ce3ede1511671c97dad61

    AttachmentFormData:
      required:
        - file
        - attachment
      type: object
      properties:
        file:
          format: binary
          description: The file to upload
          type: string
        attachment:
          $ref: "../../common/schemas/Attachment.openapi.yaml#/components/schemas/Attachment"

    AttachmentChunkForm:
      required:
        - data
      type: object
      properties:
        data:
          format: binary
          description: The file to upload
          type: string
        chunk:
          $ref: "#/components/schemas/Chunk"

    AttachmentMultipart:
      allOf:
        - $ref: "../../common/schemas/Attachment.openapi.yaml#/components/schemas/Attachment"
      required:
        - sha256
        - name
        - uploadExpectedChunks
      properties:
        uploadExpectedChunks:
          format: int32
          type: integer
          example: 3
          description: The number of chunks expected to upload
        status:
          $ref: "#/components/schemas/Status"
          readOnly: true
          description: The status of the attachment
        "@type":
          default: AttachmentMultipart
          example: AttachmentMultipart
          readOnly: true
          description: The type of the attachment
        sha256:
          description: The SHA256 hash of the attachment.
          type: string
          example: 8cf1bc0fca7f4158b8eb807be15fd7fd21bfe52d956ce3ede1511671c97dad61
        uploadChunks:
          readOnly: true
          uniqueItems: true
          type: array
          description: The chunks uploaded
          items:
            $ref: "#/components/schemas/Chunk"

    Chunk:
      type: object
      required:
        - index
        - size
        - sha256
      properties:
        index:
          format: int32
          type: integer
          description: The index of the chunk
        size:
          format: int32
          type: integer
          description: The size of the chunk
        sha256:
          type: string
          description: The SHA256 hash of the chunk

    Status:
      description: |
        The status of the attachment
        PENDING: The attachment is pending to be validated
        VALIDATED: The attachment is validated
        REJECTED: The attachment is rejected
        UPLOADING: The attachment is uploading, all chunks are not uploaded yet
      enum:
        - PENDING
        - VALIDATED
        - REJECTED
        - UPLOADING
      type: string
